# Generated by Django 5.0.3 on 2024-03-27 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('kw_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('kw_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=256)),
                ('place_addr', models.CharField(max_length=256)),
                ('place_image_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Place_Type',
            fields=[
                ('type_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_addr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contents', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TestQ',
            fields=[
                ('TQ_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_birth', models.DateField()),
                ('profile_image_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Place_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.keyword')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.place')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.place_type')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.place_type'),
        ),
        migrations.AddField(
            model_name='place',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.region'),
        ),
        migrations.AddField(
            model_name='place',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.review'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='TQ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.testq'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.place')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.place_type')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.region')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TQ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.testq')),
                ('kw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.keyword')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
    ]
