# Generated by Django 5.0.3 on 2024-04-04 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='review_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.review'),
        ),
        migrations.AddField(
            model_name='place',
            name='Bday_time',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='callNum',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='menu',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='place_url',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kw_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place_type',
            name='type_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testq',
            name='TQ_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
