# Generated by Django 5.0.3 on 2024-04-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_keyword_kw_name_alter_place_bday_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('type_id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=191, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='like',
            name='type_id',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.RemoveField(
            model_name='user_keyword',
            name='TQ_id',
        ),
        migrations.RemoveField(
            model_name='user_keyword',
            name='kw_id',
        ),
        migrations.RemoveField(
            model_name='user_keyword',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Bday_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='callNum',
        ),
        migrations.AddField(
            model_name='place',
            name='call_num',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='url',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='TQ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.testq'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kw_id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kw_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='place_id',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='region_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='review_id',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='menu',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_addr',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_image_url',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_url',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.region'),
        ),
        migrations.AlterField(
            model_name='place',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.review'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_addr',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='contents',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testq',
            name='TQ_id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testq',
            name='contents',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pw',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.CreateModel(
            name='PlaceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.keyword')),
                ('place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.place')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.placetype')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.placetype'),
        ),
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TQ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.testq')),
                ('kw_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.keyword')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Place_Keyword',
        ),
        migrations.DeleteModel(
            name='User_Keyword',
        ),
        migrations.AddField(
            model_name='place',
            name='BDay_time',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.DeleteModel(
            name='Place_Type',
        ),
    ]
