# Generated by Django 5.0.3 on 2024-04-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_placetype_alter_like_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placekeyword',
            name='TQ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_keywords', to='mysite.testq'),
        ),
        migrations.AddField(
            model_name='placekeyword',
            name='kw_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='placekeyword',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.region'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kw_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='place_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.place'),
        ),
        migrations.AlterField(
            model_name='like',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.region'),
        ),
        migrations.AlterField(
            model_name='like',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.review'),
        ),
        migrations.AlterField(
            model_name='like',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.placetype'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.user'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placekeyword',
            name='kw_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_keywords', to='mysite.keyword'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testq',
            name='TQ_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
