# Generated by Django 5.0.3 on 2024-04-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_review_date_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_id',
        ),
        migrations.AddField(
            model_name='place',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='mysite.review'),
        ),
    ]
