# Generated by Django 5.0.3 on 2024-04-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_like_region_id_remove_like_review_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placekeyword',
            name='kw_name',
        ),
    ]
